version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=BukyUsers'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: