global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    basic_auth:
      username: "prometheus"
      password: "prometheus"


  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: "user-service"
    basic_auth:
      username: 'prometheus'
      password: 'prometheus'

  - job_name: 'accommodation-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: "accommodation-service"

  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: "reservation-service"

  - job_name: 'rating-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]
        labels:
          application: "rating-service"

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]
        labels:
          application: "notification-service"