name: CI/CD
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: JDK Setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('user-service/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build And Test
        run: |
          mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/buky-users:latest


      - name: Publish Docker Image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/buky-users:latest